### ISSUE TITLE
While submitting data transaction bcdb server intermittently fails with panic

### ISSUE THREAD

**Issue by C0rWin** [hyperledger-labs/orion-server#183]
Submitting data transactions to the BCDB server fails with:

```
panic: block hash not found: 5

goroutine 126 [running]:
github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor.(*BlockProcessor).validateAndCommit(0xc0004844b0, 0xc000032f40, 0xc000032f40, 0x0)
        /go/src/github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor/processor.go:145 +0x425
github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor.(*BlockProcessor).Start(0xc0004844b0)
        /go/src/github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor/processor.go:101 +0x330
created by github.com/IBM-Blockchain/bcdb-server/internal/bcdb.newTransactionProcessor
        /go/src/github.com/IBM-Blockchain/bcdb-server/internal/bcdb/transaction_processor.go:170 +0x958
```

I'm not sure what the real root cause is, but I think that server cannot finish work with panic in a situation similar to this one, and instead of panic, it is better to log the error and reply with an internal error back to the client.

**Comment by tock-ibm** [comment]
In this case, this real panic. Block creation during commit fails when it tries to form the skip list, trying to fetch the block hash of a previous block. This should never happen, hence the panic. 

@gennadylaventman any ideas?

**Comment by C0rWin** [comment]
> This should never happen, hence the panic.

Unfortunately happened several times on pretty easy workload trying to update state.

**Comment by tock-ibm** [comment]
> Unfortunately happened several times on pretty easy workload trying to update state.

What was the deployment? single server?
How many blocks were in the ledger approximately?

**Comment by C0rWin** [comment]
> What was the deployment? single server?
> How many blocks were in the ledger approximately?

Single server, docker, 400+ blocks.

**Comment by tock-ibm** [comment]
Not encountered anymore
