### ISSUE TITLE
design and implement ACL on the provenance store

### ISSUE THREAD

**Issue by cendhu** [hyperledger-labs/orion-server#24]
Currently, we allow all BCDB users to access the provenance store. We need to decide on what a user can read such as reading provenance info of a key for which the user has read or write access. Once we decide on that, we can implement the same.

**Comment by tock-ibm** [comment]
See also #300 
- Non-admin Users should not be able to get the full ClusterConfig object
- Any admin can do full provenance on the  ClusterConfig object
